version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://salary:supersafepassword@db:5432/salary
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=salary
      - POSTGRES_PASSWORD=supersafepassword
      - POSTGRES_DB=salary
    expose:
      - 5432
