"""Add index to name search

Revision ID: 2e53875fe9b9
Revises: 5a8b906d02f4
Create Date: 2020-07-20 16:30:48.912503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e53875fe9b9"
down_revision = "5a8b906d02f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_salary_employer_city"), "salary", ["employer_city"], unique=False
    )
    op.create_index(
        op.f("ix_salary_employer_name"), "salary", ["employer_name"], unique=False
    )
    op.create_index(
        op.f("ix_salary_employer_state"), "salary", ["employer_state"], unique=False
    )
    op.create_index(
        op.f("ix_salary_employment_start_date"),
        "salary",
        ["employment_start_date"],
        unique=False,
    )
    op.create_index(op.f("ix_salary_job_title"), "salary", ["job_title"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_salary_job_title"), table_name="salary")
    op.drop_index(op.f("ix_salary_employment_start_date"), table_name="salary")
    op.drop_index(op.f("ix_salary_employer_state"), table_name="salary")
    op.drop_index(op.f("ix_salary_employer_name"), table_name="salary")
    op.drop_index(op.f("ix_salary_employer_city"), table_name="salary")
    # ### end Alembic commands ###
