"""Initial migration.

Revision ID: 5a8b906d02f4
Revises: 
Create Date: 2020-07-20 16:15:06.532496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8b906d02f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary',
    sa.Column('case_number', sa.Text(), nullable=False),
    sa.Column('case_status', sa.Text(), nullable=True),
    sa.Column('visa_class', sa.Text(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('full_time_position', sa.Text(), nullable=True),
    sa.Column('employment_start_date', sa.Date(), nullable=True),
    sa.Column('employer_name', sa.Text(), nullable=True),
    sa.Column('prevailing_wage', sa.Float(), nullable=True),
    sa.Column('employer_city', sa.Text(), nullable=True),
    sa.Column('employer_state', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('case_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary')
    # ### end Alembic commands ###
