"""Add index to name search

Revision ID: 7a44221b4dfd
Revises: 5a8b906d02f4
Create Date: 2020-07-21 14:28:49.389925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a44221b4dfd"
down_revision = "5a8b906d02f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "query_index",
        "salary",
        [
            "employer_name",
            "job_title",
            "employment_start_date",
            "employer_city",
            "employer_state",
        ],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("query_index", table_name="salary")
    # ### end Alembic commands ###
