"""empty message

Revision ID: 8053d1bdf125
Revises: 
Create Date: 2020-07-03 11:22:25.044831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8053d1bdf125'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary',
    sa.Column('CASE_NUMBER', sa.Text(), nullable=False),
    sa.Column('CASE_STATUS', sa.Text(), nullable=True),
    sa.Column('VISA_CLASS', sa.Text(), nullable=True),
    sa.Column('JOB_TITLE', sa.Text(), nullable=True),
    sa.Column('FULL_TIME_POSITION', sa.Text(), nullable=True),
    sa.Column('PERIOD_OF_EMPLOYMENT_START_DATE', sa.Text(), nullable=True),
    sa.Column('EMPLOYER_NAME', sa.Text(), nullable=True),
    sa.Column('PREVAILING_WAGE_1', sa.Integer(), nullable=True),
    sa.Column('EMPLOYER_CITY', sa.Text(), nullable=True),
    sa.Column('EMPLOYER_STATE', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('CASE_NUMBER')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary')
    # ### end Alembic commands ###
